steps:
- task: DownloadSecureFile@1
  name: SecureFile
  inputs:
    secureFile: 'SecureFile.cer'
  displayName: 'Download Secure File'

- task: CopyFile@2
  inputs:
    SourceFolder: $(Agent.TempDirectory)
    Contents: '***.cer'
    TargetFolder: $(Build.ArtifactStagingDirectory)\secrets'
  displayName: 'Copy Secure File to Artifact Staging Directory'

  
